from app.schemas import RichTagProfile


TAG_LIBRARY = [
    RichTagProfile(
        id="shangguan_peiyin",
        source_tag="伤官配印",
        display_name="灵感表达型",
        summary="才思敏捷，表达力旺盛，有创作欲，也很需要被认真理解。",
        personality_tags=["才思敏捷", "表达力旺盛", "脑洞很大", "有观点", "审美敏锐"],
        social_tags=["适合深聊", "需要被理解", "喜欢精神共鸣", "讨厌被粗暴否定"],
        career_tags=["内容创作", "策划表达", "教育传播", "咨询陪伴", "审美行业"],
        emotion_tags=["情绪丰富", "容易想太多", "夜晚思绪活跃", "灵感快闪"],
        match_preferences=["会倾听的人", "能接住情绪的人", "成熟稳定型", "同频创作者"],
        suitable_scenes=["语音匹配", "深夜聊天", "展览约会", "内容共创", "成长房间"],
        risk_notes=["容易表达过猛", "容易因为不被理解而冷掉", "需要把感受说出来"],
        match_weights={"voice": 94, "deep_chat": 96, "offline_event": 78, "creator_match": 92},
    ),
    RichTagProfile(
        id="muhuo_tongming",
        source_tag="木火通明",
        display_name="社交发光型",
        summary="表达自然，有感染力，能把关系场聊热，适合主动破冰。",
        personality_tags=["社交磁场", "表达自然", "热情直接", "灵感很多", "氛围带动者"],
        social_tags=["适合语音", "适合高频互动", "越熟越可爱", "喜欢真诚表达"],
        career_tags=["自媒体", "销售沟通", "主持传播", "品牌策划", "创意行业"],
        emotion_tags=["高能量", "容易上头", "恢复力强", "容易被氛围影响"],
        match_preferences=["稳定倾听型", "理性克制型", "能回应的人", "不扫兴的人"],
        suitable_scenes=["语音速配", "线下局", "夜晚散步", "热闹餐吧", "广场发帖"],
        risk_notes=["容易高开低走", "需要遇到能接住节奏的人", "关系里要避免过度输出"],
        match_weights={"voice": 98, "deep_chat": 88, "offline_event": 93, "creator_match": 86},
    ),
    RichTagProfile(
        id="jinshui_xiangsheng",
        source_tag="金水相生",
        display_name="冷静深聊型",
        summary="理性敏锐，适合倾听与分析，慢热但稳定，关系质感高级。",
        personality_tags=["理性敏锐", "冷静倾听", "判断清晰", "边界感强", "洞察力强"],
        social_tags=["适合慢热关系", "适合深聊", "不爱废话", "重视分寸感"],
        career_tags=["研究分析", "技术策略", "咨询顾问", "金融法务", "产品规划"],
        emotion_tags=["情绪稳定", "外冷内热", "低调敏感", "需要独处充电"],
        match_preferences=["真诚表达型", "有趣但不压迫的人", "尊重边界的人", "长期主义者"],
        suitable_scenes=["夜聊", "咖啡馆", "书店", "安静散步", "一对一语音"],
        risk_notes=["不太主动", "容易把喜欢藏起来", "需要给对方明确反馈"],
        match_weights={"voice": 82, "deep_chat": 97, "offline_event": 74, "creator_match": 80},
    ),
    RichTagProfile(
        id="qisha_ge",
        source_tag="七杀格",
        display_name="目标挑战型",
        summary="行动力强，有野心，喜欢强者对话，也需要柔和稳定的人平衡。",
        personality_tags=["行动力强", "目标感强", "不服输", "有野心", "抗压能力强"],
        social_tags=["喜欢强者对话", "适合成长搭子", "讨厌拖泥带水", "关系里直接"],
        career_tags=["创业", "管理", "商务拓展", "竞技挑战", "项目攻坚"],
        emotion_tags=["容易紧绷", "压力下爆发", "不轻易示弱", "需要被信任"],
        match_preferences=["温柔稳定型", "高认知型", "能一起成长的人", "不内耗的人"],
        suitable_scenes=["事业话题", "运动局", "挑战活动", "成长房间", "目标打卡"],
        risk_notes=["容易控制感过强", "需要练习放松", "关系中要少用命令语气"],
        match_weights={"voice": 78, "deep_chat": 84, "offline_event": 91, "creator_match": 72},
    ),
    RichTagProfile(
        id="shishen_shengcai",
        source_tag="食神生财",
        display_name="松弛生活型",
        summary="会享受生活，审美和创造力稳定，关系里舒服、耐心、好相处。",
        personality_tags=["松弛感", "审美在线", "稳定输出", "会照顾人", "生活感强"],
        social_tags=["适合轻松陪伴", "适合慢慢培养", "喜欢自然相处", "越处越舒服"],
        career_tags=["美食生活", "设计审美", "品牌运营", "手作创意", "内容种草"],
        emotion_tags=["情绪柔和", "恢复力强", "不喜欢高压", "需要舒适节奏"],
        match_preferences=["舒服自然的人", "不催促的人", "有生活热情的人", "稳定回应型"],
        suitable_scenes=[" brunch", "市集", "公园", "做饭局", "生活分享"],
        risk_notes=["容易拖延", "要避免过度求舒服", "需要把计划落地"],
        match_weights={"voice": 80, "deep_chat": 83, "offline_event": 89, "creator_match": 85},
    ),
]
