import { randomUUID } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { analyzeBirth, analyzeDuoRhythm, analyzeRelationship, validateBirth, type DuoYearOutlook } from "./fate";
import { buildDuoFacts, type DuoFacts } from "./duo";
import { UpstreamTimeoutError, generateDuoDigest, translateToEnglish } from "./duoGenerate";
import { buildReportPdf } from "./reportPdf";
import type { BirthInput, RelationshipAnalysis } from "./types";

// Agent 报告管线（OKX 黑客松：买方 agent 经 Hermes 店员下单，本模块是后厨）。
// 任务制：POST 建任务立即返回，轮询取货；同一对盘缓存成品，不重复烧 AI。
// 双语范围（用户拍板）：目录与免责声明走固定对照表，执行摘要走一次翻译调用；章节正文中文。

export type AgentReportInput = { a: BirthInput; b: BirthInput; relationType: string; bilingual: boolean };

export type AgentReportJson = {
  reportId: string;
  generatedAt: string;
  brand: string;
  relationType: string;
  persons: DuoFacts["persons"];
  score: number;
  verdict: RelationshipAnalysis["guide"]["verdict"];
  scoreBreakdown: RelationshipAnalysis["scoreBreakdown"];
  toc: { no: string; zh: string; en: string }[];
  summary: { zh: string; en?: string };
  chapters: {
    overview: { thesis: string; scoreSummary: string };
    nature: { manuals: RelationshipAnalysis["guide"]["manuals"]; diffs: { label: string; a: number; b: number; aReading: string; bReading: string }[] };
    structure: RelationshipAnalysis["branchDynamics"];
    manner: RelationshipAnalysis["guide"]["behaviors"];
    reef: { philosophy: string; hotspots: RelationshipAnalysis["guide"]["hotspots"] };
    rhythm: DuoYearOutlook[];
  };
  book: { source: "ai" | "fallback"; headline: string; pages: Record<string, { essay: string; advice: string }> };
  disclaimer: { zh: string; en: string };
};

export type AgentReportJob = {
  id: string;
  status: "processing" | "done" | "failed";
  step: string;
  error?: string;
  createdAt: number;
  bilingual: boolean;
  result?: { reportId: string; pdfPath: string; report: AgentReportJson };
};

export const REPORT_TOC: { no: string; zh: string; en: string }[] = [
  { no: "壹", zh: "关系总览", en: "Relationship Overview" },
  { no: "贰", zh: "两人底色", en: "Two Blueprints: Manuals & Differences" },
  { no: "叁", zh: "八字化学反应", en: "Chart Chemistry: Structural Dynamics" },
  { no: "肆", zh: "相处样态", en: "Everyday Patterns" },
  { no: "伍", zh: "摩擦与化解", en: "Frictions & Remedies" },
  { no: "陆", zh: "未来五年", en: "The Next Five Years" },
  { no: "柒", zh: "深度评述五章", en: "In-Depth Essays (Five Parts)" },
];

export const DISCLAIMER_ZH = "免责声明：本报告由 FATE 模型 2.0 基于传统历法结构与行为模型推演生成，内容仅供娱乐与自我认知参考，不构成婚恋、医疗、心理、法律或投资建议，不作任何吉凶祸福的断言或承诺。报告描述的是倾向与节律，真实的关系由两个人的真实相处决定。";
export const DISCLAIMER_EN = "Disclaimer: This report is generated by FATE Model 2.0 based on traditional calendrical structures and behavioral modeling. It is intended for entertainment and self-reflection only, and does not constitute relationship, medical, psychological, legal, or financial advice. It makes no claims or promises about fortune or misfortune. The report describes tendencies and rhythms; real relationships are shaped by how two people actually treat each other.";

const globalStore = globalThis as unknown as { __fateAgentJobs?: Map<string, AgentReportJob>; __fateAgentCache?: Map<string, string> };
const jobs = (globalStore.__fateAgentJobs ??= new Map<string, AgentReportJob>());
const doneCache = (globalStore.__fateAgentCache ??= new Map<string, string>());

const REPORT_DIR = path.join(process.cwd(), ".reports");

export function getJob(id: string): AgentReportJob | undefined {
  return jobs.get(id);
}

export function createReportJob(input: AgentReportInput): { job: AgentReportJob; cached: boolean } {
  const profileA = analyzeBirth(input.a);
  const profileB = analyzeBirth(input.b);
  const pairKey = `${profileA.id}-${profileB.id}-${input.relationType}-${input.bilingual ? "bi" : "zh"}`;
  const cachedId = doneCache.get(pairKey);
  if (cachedId) {
    const cachedJob = jobs.get(cachedId);
    if (cachedJob?.status === "done") return { job: cachedJob, cached: true };
  }
  const job: AgentReportJob = { id: randomUUID(), status: "processing", step: "排盘", createdAt: Date.now(), bilingual: input.bilingual };
  jobs.set(job.id, job);
  void runPipeline(job, input, pairKey);
  return { job, cached: false };
}

// 摘要合成：确定性中文底稿（判词/最强最弱维/首要雷区/五年主线/成册标题），合规口径
function composeSummaryZh(analysis: RelationshipAnalysis, rhythm: DuoYearOutlook[], bookHeadline: string, names: [string, string]): string {
  const dims = [...analysis.scoreBreakdown].sort((x, y) => y.score - x.score);
  const best = dims[0];
  const worst = dims[dims.length - 1];
  const hotspot = analysis.guide.hotspots[0];
  const rhythmLine = rhythm.map((y) => `${y.year} 年偏${y.tendencies[0]?.label ?? "平稳"}`).join("、");
  return [
    `${names[0]}与${names[1]}的${analysis.relationType}合盘，综合评分 ${analysis.score} 分，关系判词「${analysis.guide.verdict.title}」——${analysis.guide.verdict.tagline}`,
    `六维之中，${best.label}最高（${best.score} 分），${worst.label}最低（${worst.score} 分）；最需要留意的摩擦情境是「${hotspot.scene}」，${hotspot.source}。`,
    `未来五年节律：${rhythmLine}。`,
    `深度评述以「${bookHeadline}」开卷，五章正文详见报告。`,
  ].join("\n");
}

async function runPipeline(job: AgentReportJob, input: AgentReportInput, pairKey: string) {
  try {
    job.step = "排盘与规则引擎";
    const profileA = analyzeBirth(input.a);
    const profileB = analyzeBirth(input.b);
    const analysis = analyzeRelationship(profileA, profileB, input.relationType);
    const facts = buildDuoFacts(profileA, profileB, analysis);
    const rhythm = analyzeDuoRhythm(profileA, profileB, input.relationType, new Date().getFullYear(), 5);
    const nameA = facts.persons[0].name;
    const nameB = facts.persons[1].name;

    // 贰章差异三处（与页面同口径：深度报告差值最大的维度）
    const diffs = profileA.deepAnalysis
      .map((item) => {
        const other = profileB.deepAnalysis.find((entry) => entry.key === item.key);
        return other ? { label: item.label, a: item.score, b: other.score, aReading: `${item.descriptor}：${item.summary}`, bReading: `${other.descriptor}：${other.summary}`, gap: Math.abs(item.score - other.score) } : null;
      })
      .filter((pair): pair is NonNullable<typeof pair> => pair !== null)
      .sort((x, y) => y.gap - x.gap)
      .slice(0, 3)
      .map(({ gap: _gap, ...rest }) => rest);

    job.step = "深度评述生成（约一到两分钟）";
    const { source, digest } = await generateDuoDigest(facts);

    job.step = "摘要合成";
    const summaryZh = composeSummaryZh(analysis, rhythm, digest.headline, [nameA, nameB]);
    let summaryEn: string | undefined;
    if (input.bilingual) {
      job.step = "摘要翻译";
      summaryEn = await translateToEnglish(summaryZh);
    }

    const reportId = `FATE-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, "0")}${String(new Date().getDate()).padStart(2, "0")}-${job.id.slice(0, 8).toUpperCase()}`;
    const report: AgentReportJson = {
      reportId,
      generatedAt: new Date().toISOString(),
      brand: "FATE° · 东方人格建模系统 · FATE Model 2.0",
      relationType: input.relationType,
      persons: facts.persons,
      score: analysis.score,
      verdict: analysis.guide.verdict,
      scoreBreakdown: analysis.scoreBreakdown,
      toc: REPORT_TOC,
      summary: { zh: summaryZh, ...(summaryEn ? { en: summaryEn } : {}) },
      chapters: {
        overview: { thesis: analysis.spine.thesis, scoreSummary: analysis.scoreSummary },
        nature: { manuals: analysis.guide.manuals, diffs },
        structure: analysis.branchDynamics,
        manner: analysis.guide.behaviors,
        reef: { philosophy: analysis.guide.philosophy, hotspots: analysis.guide.hotspots },
        rhythm,
      },
      book: { source, headline: digest.headline, pages: digest.pages },
      disclaimer: { zh: DISCLAIMER_ZH, en: DISCLAIMER_EN },
    };

    job.step = "排版 PDF";
    const pdfBuffer = await buildReportPdf(report, { bilingual: input.bilingual, names: [nameA, nameB] });
    mkdirSync(REPORT_DIR, { recursive: true });
    const pdfPath = path.join(REPORT_DIR, `${reportId}.pdf`);
    writeFileSync(pdfPath, pdfBuffer);

    job.result = { reportId, pdfPath, report };
    job.status = "done";
    job.step = "完成";
    doneCache.set(pairKey, job.id);
  } catch (error) {
    job.status = "failed";
    job.error = error instanceof UpstreamTimeoutError ? error.message : `生成失败：${error instanceof Error ? error.message : String(error)}`;
    job.step = "失败";
  }
}

export function validateAgentInput(body: unknown): { input?: AgentReportInput; error?: string } {
  const raw = body as { a?: BirthInput; b?: BirthInput; relationType?: string; bilingual?: boolean } | null;
  if (!raw?.a || !raw?.b) return { error: "需要 a、b 两个人的出生信息（year/month/day/hour[/minute/gender/calendarType/name]）。" };
  const errorA = validateBirth(raw.a);
  if (errorA) return { error: `a 无效：${errorA}` };
  const errorB = validateBirth(raw.b);
  if (errorB) return { error: `b 无效：${errorB}` };
  const relationType = raw.relationType ?? "恋爱";
  if (!["恋爱", "朋友", "同事", "家人"].includes(relationType)) return { error: "relationType 仅支持：恋爱 / 朋友 / 同事 / 家人。" };
  return { input: { a: raw.a, b: raw.b, relationType, bilingual: raw.bilingual !== false } };
}
