import { randomUUID } from "node:crypto";
import { analyzeBirth, analyzeDuoRhythm, analyzeRelationship, validateBirth, type DuoYearOutlook } from "./fate";
import { buildDuoFacts, type DuoFacts } from "./duo";
import { UpstreamTimeoutError, generateDuoDigest, translateBatch } from "./duoGenerate";
import { buildReportPdf, type BaziChart, type Bi, type ReportBlock } from "./reportPdf";
import type { BirthInput, RelationshipAnalysis, UserProfile } from "./types";

// Agent 报告管线（OKX 黑客松：买方 agent 经 Hermes 店员下单，本模块是后厨）。
// 任务制：POST 建任务立即返回，轮询取货；同盘成品缓存。
// 双语（用户拍板「做全套」）：PDF 全内容双语 + 双方四柱命盘；中文正文一次性批量翻译。

export type AgentReportInput = { a: BirthInput; b: BirthInput; relationType: string; bilingual: boolean };

export type AgentReportJson = {
  reportId: string;
  generatedAt: string;
  brand: string;
  relationType: string;
  persons: DuoFacts["persons"];
  charts: BaziChart[];
  score: number;
  verdict: RelationshipAnalysis["guide"]["verdict"];
  scoreBreakdown: RelationshipAnalysis["scoreBreakdown"];
  toc: { no: string; zh: string; en: string }[];
  summary: { zh: string; en?: string };
  chapters: {
    overview: { thesis: string; scoreSummary: string };
    nature: { manuals: RelationshipAnalysis["guide"]["manuals"]; diffs: { label: string; a: number; b: number; aReading: string; bReading: string }[] };
    structure: RelationshipAnalysis["branchDynamics"];
    manner: RelationshipAnalysis["guide"]["behaviors"];
    reef: { philosophy: string; hotspots: RelationshipAnalysis["guide"]["hotspots"] };
    rhythm: DuoYearOutlook[];
  };
  book: { source: "ai" | "fallback"; headline: string; pages: Record<string, { essay: string; advice: string }> };
  disclaimer: { zh: string; en: string };
};

export type AgentReportJob = {
  id: string;
  status: "processing" | "done" | "failed";
  step: string;
  error?: string;
  createdAt: number;
  bilingual: boolean;
  result?: { reportId: string; pdf: Buffer; report: AgentReportJson };
};

export const REPORT_TOC: { no: string; zh: string; en: string }[] = [
  { no: "壹", zh: "关系总览", en: "Relationship Overview" },
  { no: "贰", zh: "两人底色", en: "Two Blueprints — Manuals & Differences" },
  { no: "叁", zh: "八字化学反应", en: "Chart Chemistry — Structural Dynamics" },
  { no: "肆", zh: "相处样态", en: "Everyday Patterns" },
  { no: "伍", zh: "摩擦与化解", en: "Frictions & Remedies" },
  { no: "陆", zh: "未来五年", en: "The Next Five Years" },
  { no: "柒", zh: "深度评述五章", en: "In-Depth Essays — Five Parts" },
];

export const DISCLAIMER_ZH = "免责声明：本报告由 FATE 模型 2.0 基于传统历法结构与行为模型推演生成，内容仅供娱乐与自我认知参考，不构成婚恋、医疗、心理、法律或投资建议，不作任何吉凶祸福的断言或承诺。报告描述的是倾向与节律，真实的关系由两个人的真实相处决定。";
export const DISCLAIMER_EN = "Disclaimer: This report is generated by FATE Model 2.0 based on traditional calendrical structures and behavioral modeling. It is intended for entertainment and self-reflection only, and does not constitute relationship, medical, psychological, legal, or financial advice. It makes no claim or promise about fortune or misfortune. It describes tendencies and rhythms; a real relationship is shaped by how two people actually treat each other.";

// 固定术语表：命理与指标名用固定英文，避免逐次翻译漂移；表外词条走 API
const GLOSSARY: Record<string, string> = {
  初见引力: "First Attraction", 情绪承接: "Emotional Holding", 表达译码: "Expression Decoding", 主导权协商: "Power Negotiation", 日常黏合: "Daily Cohesion", 冲突修复: "Conflict Repair",
  外向表达: "Extroversion", 社交开放: "Social Openness", 食伤强度: "Output Strength", 浪漫主动: "Romantic Initiative", 新鲜感: "Novelty", 情感强度: "Emotional Intensity", 边界控制: "Boundary Control",
  官杀强度: "Authority Strength", 印星强度: "Resource Strength", 情感依赖: "Dependency", 关系主动性: "Relational Initiative", 财星强度: "Wealth Strength", 关系警觉: "Vigilance",
  情绪稳定: "Emotional Stability", 冲突表达: "Conflict Expression", 压力韧性: "Stress Resilience", 信任建立: "Trust-building", 空间需求: "Need for Space", 破冰主动: "Ice-breaking Initiative",
  信任建立速度: "Trust-building Speed", 自主与空间需求: "Autonomy & Space", 变动: "Change", 动荡: "Turbulence", 推进: "Advancement", 外缘: "Outside Attention", 人缘: "Social Draw", 耗损: "Depletion",
};

const CHAPTER_EN: Record<string, string> = { 关系总览: "Relationship Overview", 两人底色: "Two Blueprints", 八字化学反应: "Chart Chemistry", 相处样态: "Everyday Patterns", 摩擦与化解: "Frictions & Remedies", 未来五年: "The Next Five Years", 深度评述: "In-Depth Essays" };
const BOOK_PAGE_EN: Record<string, string> = { origin: "Origin", daily: "Daily Life", friction: "Friction", longrun: "Long Run", season: "Seasons" };
const BOOK_PAGE_ZH: Record<string, string> = { origin: "缘起", daily: "相处", friction: "摩擦", longrun: "长线", season: "时运" };

const globalStore = globalThis as unknown as { __fateAgentJobs?: Map<string, AgentReportJob> };
const jobs = (globalStore.__fateAgentJobs ??= new Map<string, AgentReportJob>());
const DEFAULT_JOB_TTL_MS = 10 * 60 * 1000;

function jobTtlMs(): number {
  const configured = Number(process.env.AGENT_REPORT_TTL_SECONDS);
  return Number.isInteger(configured) && configured >= 60 && configured <= 15 * 60
    ? configured * 1000
    : DEFAULT_JOB_TTL_MS;
}

function expireJob(jobId: string) {
  setTimeout(() => jobs.delete(jobId), jobTtlMs());
}

export function getJob(id: string): AgentReportJob | undefined { return jobs.get(id); }

export function createReportJob(input: AgentReportInput): { job: AgentReportJob; cached: boolean } {
  const job: AgentReportJob = { id: randomUUID(), status: "processing", step: "排盘", createdAt: Date.now(), bilingual: input.bilingual };
  jobs.set(job.id, job);
  void runPipeline(job, input);
  return { job, cached: false };
}

const ELEMENT_CN: Record<string, string> = { wood: "木", fire: "火", earth: "土", metal: "金", water: "水" };
function chartOf(profile: UserProfile, name: string, attachment: string): BaziChart {
  const dm = profile.energy.dayMaster;
  return {
    name,
    dayMaster: `${profile.bazi.dayPillar[0]}${ELEMENT_CN[dm.element] ?? ""}`,
    strength: dm.level,
    favorable: (dm.favorable ?? []).map((e) => ELEMENT_CN[e] ?? e).join("、"),
    attachment,
    pillars: profile.bazi.pillars.map((p) => ({
      label: p.label, gan: p.gan, zhi: p.zhi, tenGod: p.tenGod,
      hidden: p.hiddenStems.join(""), hiddenGods: p.hiddenTenGods.join("·"), wuXing: p.wuXing, stage: p.stage,
    })),
  };
}

function composeSummaryZh(analysis: RelationshipAnalysis, rhythm: DuoYearOutlook[], bookHeadline: string, names: [string, string]): string {
  const dims = [...analysis.scoreBreakdown].sort((x, y) => y.score - x.score);
  const best = dims[0], worst = dims[dims.length - 1];
  const hotspot = analysis.guide.hotspots[0];
  const rhythmLine = rhythm.map((y) => `${y.year} 年偏${y.tendencies[0]?.label ?? "平稳"}`).join("、");
  return [
    `${names[0]}与${names[1]}的${analysis.relationType}合盘，综合评分 ${analysis.score} 分，关系判词「${analysis.guide.verdict.title}」——${analysis.guide.verdict.tagline}`,
    `六维之中，${best.label}最高，${worst.label}最低；最需要留意的摩擦情境是「${hotspot.scene}」，${hotspot.source}。`,
    `未来五年节律：${rhythmLine}。`,
    `深度评述以「${bookHeadline}」开卷，五章正文详见报告。`,
  ].join("\n");
}

async function runPipeline(job: AgentReportJob, input: AgentReportInput) {
  try {
    job.step = "排盘与规则引擎";
    const profileA = analyzeBirth(input.a);
    const profileB = analyzeBirth(input.b);
    const analysis = analyzeRelationship(profileA, profileB, input.relationType);
    const facts = buildDuoFacts(profileA, profileB, analysis);
    const rhythm = analyzeDuoRhythm(profileA, profileB, input.relationType, new Date().getFullYear(), 5);
    const nameA = facts.persons[0].name, nameB = facts.persons[1].name;
    const charts: [BaziChart, BaziChart] = [chartOf(profileA, nameA, facts.persons[0].attachment), chartOf(profileB, nameB, facts.persons[1].attachment)];

    const diffs = profileA.deepAnalysis
      .map((item) => {
        const other = profileB.deepAnalysis.find((entry) => entry.key === item.key);
        return other ? { label: item.label, a: item.score, b: other.score, aReading: `${item.descriptor}：${item.summary}`, bReading: `${other.descriptor}：${other.summary}`, gap: Math.abs(item.score - other.score) } : null;
      })
      .filter((pair): pair is NonNullable<typeof pair> => pair !== null)
      .sort((x, y) => y.gap - x.gap).slice(0, 3).map(({ gap: _gap, ...rest }) => rest);

    // 成册评述立即开跑，先不 await——趁它生成，把不依赖它的前六章先翻掉（重叠，省近一半墙钟）
    job.step = "生成评述 · 同时翻译前六章";
    const digestPromise = generateDuoDigest(facts);

    // ── 组装双语 blocks：前六章（规则引擎，不依赖成册）先翻；摘要+评述待成册后再翻 ──
    const cache = new Map<string, Bi>();
    let pending: Bi[] = [];
    const bi = (zh: string): Bi => {
      const trimmed = (zh ?? "").trim();
      const hit = cache.get(trimmed);
      if (hit) return hit;
      const seeded = GLOSSARY[trimmed];
      const entry: Bi = { zh: trimmed, en: seeded ?? "" };
      cache.set(trimmed, entry);
      if (!seeded && trimmed) pending.push(entry);
      return entry;
    };
    const drainAndTranslate = async (label: string) => {
      const batch = pending; pending = []; // 同步截断本波，后续新增归下一波
      if (!input.bilingual || !batch.length) return;
      job.step = label;
      const translations = await translateBatch(batch.map((entry) => entry.zh));
      batch.forEach((entry, index) => { entry.en = translations[index] ?? entry.en; });
    };
    const chapterTitle = (zh: string): Bi => ({ zh, en: CHAPTER_EN[zh] ?? zh });
    const toneOfImpact = (impact: number) => impact > 0 ? "green" as const : "pink" as const;
    const toneOfTendency = (key: string) => key === "advance" ? "green" as const : key === "turbulence" ? "pink" as const : "gold" as const;

    const midBlocks: ReportBlock[] = [];
    const push = (b: ReportBlock) => midBlocks.push(b);

    // 壹 关系总览
    push({ t: "chapter", no: "壹", title: chapterTitle("关系总览") });
    push({ t: "para", text: bi(`综合评分 ${analysis.score} 分——${analysis.spine.thesis}。`) });
    push({ t: "small", text: bi(analysis.scoreSummary) });
    push({ t: "bars", items: analysis.scoreBreakdown.map((dim) => ({ label: bi(dim.label), a: dim.score, tone: "green" as const })) });
    push({ t: "small", text: bi(`判据：${analysis.guide.verdict.basis} —— ${analysis.guide.verdict.tagline}`) });

    // 贰 两人底色
    push({ t: "chapter", no: "贰", title: chapterTitle("两人底色") });
    push({ t: "h2", title: { zh: "你们最不一样的三处", en: "Your Three Biggest Differences" } });
    for (const diff of diffs) {
      push({ t: "bars", legend: [nameA, nameB], items: [{ label: bi(diff.label), a: diff.a, b: diff.b }] });
      push({ t: "small", text: bi(`${nameA} · ${diff.aReading}`) });
      push({ t: "small", text: bi(`${nameB} · ${diff.bReading}`) });
      push({ t: "spacer" });
    }
    for (const manual of analysis.guide.manuals) {
      push({ t: "h2", title: { zh: `${manual.person} 使用说明书`, en: `A User's Manual for ${manual.person}` } });
      for (const entry of manual.dos) push({ t: "do", text: bi(entry) });
      for (const entry of manual.donts) push({ t: "dont", text: bi(entry) });
      push({ t: "spacer" });
    }

    // 叁 八字化学反应
    push({ t: "chapter", no: "叁", title: chapterTitle("八字化学反应") });
    if (!analysis.branchDynamics.length) push({ t: "para", text: bi("两张命盘之间没有形成明显的六合、六冲、三合、三会或天干相克，互动重点更多落在双方十神与行为维度。") });
    for (const dynamic of analysis.branchDynamics) {
      push({ t: "h2", title: bi(`${dynamic.type} · ${dynamic.title}`) });
      push({ t: "small", text: bi(`${nameA}：${dynamic.userPillars.join("、")}　${nameB}：${dynamic.partnerPillars.join("、")}　${dynamic.scoreImpact > 0 ? "增益结构" : "压力结构"}`) });
      push({ t: "bars", items: [{ label: { zh: "结构强度", en: "Structural Strength" }, a: dynamic.strength, tone: toneOfImpact(dynamic.scoreImpact) }] });
      push({ t: "para", text: bi(dynamic.summary) });
      push({ t: "small", text: bi(dynamic.scenarioImpact) });
      push({ t: "small", text: bi(`怎么相处：${dynamic.advice}`) });
      push({ t: "divider" });
    }

    // 肆 相处样态
    push({ t: "chapter", no: "肆", title: chapterTitle("相处样态") });
    push({ t: "small", text: { zh: `对比条：绿＝${nameA}，粉＝${nameB}`, en: `Bars: green = ${nameA}, pink = ${nameB}` } });
    for (const behavior of analysis.guide.behaviors) {
      push({ t: "h2", title: bi(`${behavior.label} —— ${behavior.conclusion}`) });
      push({ t: "small", text: bi(behavior.basis) });
      push({ t: "bars", items: behavior.metrics.map((m) => ({ label: bi(m.label), a: m.a, b: m.b })) });
      push({ t: "spacer" });
    }

    // 伍 摩擦与化解
    push({ t: "chapter", no: "伍", title: chapterTitle("摩擦与化解") });
    push({ t: "small", text: bi(analysis.guide.philosophy) });
    analysis.guide.hotspots.forEach((hotspot, index) => {
      push({ t: "h2", title: bi(`0${index + 1} ${hotspot.scene}`) });
      push({ t: "small", text: bi(hotspot.source) });
      push({ t: "bars", items: hotspot.metrics.map((m) => ({ label: bi(m.label), a: m.a, b: m.b })) });
      push({ t: "para", text: bi(hotspot.risk) });
      push({ t: "small", text: bi(`拆法：${hotspot.playbook}`) });
      push({ t: "divider" });
    });

    // 陆 未来五年
    push({ t: "chapter", no: "陆", title: chapterTitle("未来五年") });
    push({ t: "small", text: { zh: "逐年只列倾向：倾向值与触发它的结构信号。节律供安排节奏参考，不作吉凶断言。", en: "Each year lists only tendencies — a score plus the structural signals behind it. For pacing reference, not fortune-telling." } });
    for (const year of rhythm) {
      push({ t: "h2", title: { zh: `${year.year} ${year.ganZhi} —— ${year.tendencies[0] ? `${year.tendencies[0].label}倾向为主` : "无强倾向"}`, en: `${year.year} ${year.ganZhi} — ${year.tendencies[0] ? `mainly ${GLOSSARY[year.tendencies[0].label] ?? year.tendencies[0].label}` : "no strong tendency"}` } });
      push({ t: "bars", items: year.tendencies.map((tendency) => ({ label: bi(`${tendency.label}倾向`), a: tendency.value, tone: toneOfTendency(tendency.key) })) });
      push({ t: "small", text: bi(`信号：${year.tendencies.flatMap((tendency) => tendency.causes.map((c) => `${c.who}·${c.label}`)).join("、") || "无"}`) });
      push({ t: "para", text: bi(year.reading) });
      push({ t: "small", text: bi(`这一年怎么过：${year.advice}`) });
      push({ t: "divider" });
    }

    // 前六章已入 midBlocks——先启动它们的翻译（第一波），与仍在生成的成册评述并行推进
    const midTranslate = drainAndTranslate("翻译前六章 · 同时等评述");
    const { source, digest } = await digestPromise;
    const summaryZh = composeSummaryZh(analysis, rhythm, digest.headline, [nameA, nameB]);

    // 执行摘要（置于报告最前）
    const headBlocks: ReportBlock[] = [
      { t: "h2", title: { zh: "执行摘要", en: "Executive Summary" } },
      { t: "para", text: bi(summaryZh) },
      { t: "spacer" },
    ];

    // 柒 深度评述（依赖成册）
    const tailBlocks: ReportBlock[] = [];
    const tpush = (b: ReportBlock) => tailBlocks.push(b);
    tpush({ t: "chapter", no: "柒", title: chapterTitle("深度评述") });
    tpush({ t: "h2", title: bi(`「${digest.headline}」`) });
    for (const [key, page] of Object.entries(digest.pages)) {
      tpush({ t: "h2", title: { zh: BOOK_PAGE_ZH[key] ?? key, en: BOOK_PAGE_EN[key] ?? key } });
      tpush({ t: "para", text: bi(page.essay) });
      tpush({ t: "small", text: bi(`一起做的一件事：${page.advice}`) });
      tpush({ t: "spacer" });
    }

    // 第二波：摘要 + 评述翻译；再等第一波（前六章）收尾
    await drainAndTranslate("翻译摘要与评述");
    await midTranslate;
    const blocks: ReportBlock[] = [...headBlocks, ...midBlocks, ...tailBlocks];

    const reportId = `FATE-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, "0")}${String(new Date().getDate()).padStart(2, "0")}-${job.id.slice(0, 8).toUpperCase()}`;
    const generatedAt = new Date().toISOString().replace("T", " ").slice(0, 16) + " UTC";
    const summaryBi = cache.get(summaryZh.trim());

    const report: AgentReportJson = {
      reportId, generatedAt, brand: "FATE° · 东方人格建模系统 · FATE Model 2.0",
      relationType: input.relationType, persons: facts.persons, charts, score: analysis.score,
      verdict: analysis.guide.verdict, scoreBreakdown: analysis.scoreBreakdown, toc: REPORT_TOC,
      summary: { zh: summaryZh, ...(summaryBi?.en ? { en: summaryBi.en } : {}) },
      chapters: {
        overview: { thesis: analysis.spine.thesis, scoreSummary: analysis.scoreSummary },
        nature: { manuals: analysis.guide.manuals, diffs },
        structure: analysis.branchDynamics, manner: analysis.guide.behaviors,
        reef: { philosophy: analysis.guide.philosophy, hotspots: analysis.guide.hotspots }, rhythm,
      },
      book: { source, headline: digest.headline, pages: digest.pages },
      disclaimer: { zh: DISCLAIMER_ZH, en: DISCLAIMER_EN },
    };

    job.step = "排版 PDF";
    const pdfBuffer = await buildReportPdf({
      meta: { reportId, generatedAt, relationType: input.relationType, names: [nameA, nameB], verdictTitle: analysis.guide.verdict.title, verdictQuip: analysis.guide.verdict.quip, disclaimerZh: DISCLAIMER_ZH, disclaimerEn: DISCLAIMER_EN },
      charts, toc: REPORT_TOC, blocks,
    });
    job.result = { reportId, pdf: pdfBuffer, report };
    job.status = "done";
    job.step = "完成";
    // Keep the asynchronous delivery in process memory only, then discard it.
    expireJob(job.id);
  } catch (error) {
    job.status = "failed";
    job.error = error instanceof UpstreamTimeoutError ? "上游生成或翻译超时，请稍后重试。" : `生成失败：${error instanceof Error ? error.message : String(error)}`;
    job.step = "失败";
    expireJob(job.id);
  }
}

export function validateAgentInput(body: unknown): { input?: AgentReportInput; error?: string } {
  const raw = body as { a?: BirthInput; b?: BirthInput; relationType?: string; bilingual?: boolean } | null;
  if (!raw?.a || !raw?.b) return { error: "需要 a、b 两个人的出生信息（year/month/day/hour[/minute/gender/calendarType/name]）。" };
  const errorA = validateBirth(raw.a);
  if (errorA) return { error: `a 无效：${errorA}` };
  const errorB = validateBirth(raw.b);
  if (errorB) return { error: `b 无效：${errorB}` };
  const relationType = raw.relationType ?? "恋爱";
  if (!["恋爱", "朋友", "同事", "家人"].includes(relationType)) return { error: "relationType 仅支持：恋爱 / 朋友 / 同事 / 家人。" };
  return { input: { a: raw.a, b: raw.b, relationType, bilingual: raw.bilingual !== false } };
}
